name: client
run-name: exercice
on: push
jobs:
    check-bats-version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: gcc server_prev.c -o server
            - run: gcc client_prev.c -o ./clientd/client
            - run: gcc ./producteur/test/prod_cons.c -o ./producteur/test/prod
